# Generated by Django 5.2.17 on 2026-09-07 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, help_text='Original report text as pasted/uploaded')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('category', models.CharField(choices=[('blood_test', 'Blood Test'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('reviewed', 'Reviewed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
