# Generated by Django 5.2.17 on 2026-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text automatically extracted from the uploaded file'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
