# Generated by Django 5.2.17 on 2026-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_extracted_text_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
